# Generated by Django 3.2.22 on 2023-12-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='photos/')),
                ('file_url', models.URLField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
